# Библиотека Numpy.
- ***``Numpy`` - это библиотека Python для вычислительно эффективных операций с многомерными массивами, предназначенная в основном для научных вычислений.***


- ***Пакет ``Numpy`` предоставляет $n$-мерные однородные массивы (все элементы одного типа) в них нельзя вставить или удалить элемент в произвольном месте. В ``Numpy`` реализовано много операций над массивами в целом.***

In [37]:
import numpy as np

# Работа с массивами

***Задание:***
- Отобразить вектор размера 100, в котором вычеркивается **x**, если **x** --- составное (т. е. не является простым)

In [38]:
is_prime = np.ones(100, dtype=bool)

In [39]:
is_prime[:2] = False

In [40]:
N_max = int(np.sqrt(len(is_prime)))
for i in range(2, N_max):
    is_prime[2*i::i] = False # начинаем с 2i с шагом i

print(is_prime)

[False False  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False False False False  True False False False  True
 False  True False False False False False  True False False False  True
 False False False False False  True False False False False False False
 False  True False False]


In [41]:
print(is_prime[17])
print(is_prime[25])

True
False


***Маски.***

In [42]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


***След (trace) - сумма диагональных элементов.***

In [43]:
b = np.diag(a[a >= 10])
print(b)
print(np.trace(b))

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


# Тензоры (многомерные массивы)

Тензор - это более общий термин и означает многомерный массив с более чем двумя измерениями.

Примерами могут служить изображения (где у нас есть две пространственные оси и, возможно, канальная ось), видео (где к каждому изображению добавляется временная ось), и данные с дополнительными измерениями.

In [44]:
import numpy as np

In [45]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


In [46]:
X.shape

(8, 2, 4)

In [47]:
X.shape, len(X), X.size, X.ndim

((8, 2, 4), 8, 64, 3)

***Посмотрим на суммы по разным осям.***

In [48]:
print(np.sum(X, axis=0), '\n') # 0 - ширина матрицы или тензора
print(np.sum(X, axis=1), '\n') # 1 - высота матрицы или тензора
print(np.sum(X, axis=2), '\n') # 2 - глубина 

# суммируем сразу по двум осям, то есть для фиксированной i
# суммируем только элементы с индексами (i, *, *)
print(np.sum(X, axis=(1, 2)))

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 

[ 28  92 156 220 284 348 412 476]


# Линейная алгебра

In [49]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


***Определитель.***

In [50]:
np.linalg.det(a)

np.float64(4.0)

***Нахождениия обратной.***

In [51]:
a

array([[2, 1],
       [2, 3]])

In [52]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [53]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [54]:
a @ b

array([[1., 0.],
       [0., 1.]])

In [55]:
b @ a

array([[1., 0.],
       [0., 1.]])

In [56]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


In [57]:
c

array([[2, 1],
       [6, 3]])

In [58]:
np.linalg.inv(c) # предполагается ошибка

LinAlgError: Singular matrix

***Решение НЛУ.***
$$ A \cdot x = v $$

In [21]:
a

array([[2, 1],
       [2, 3]])

In [23]:
b # b = np.linalg.inv(a)

array([[ 0.75, -0.25],
       [-0.5 ,  0.5 ]])

In [24]:
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(b.dot(v))

[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


***Найдем собственные вектора матрицы A.***
$$ A \cdot x = \lambda \cdot x $$

In [25]:
a

array([[2, 1],
       [2, 3]])

In [ ]:
l, u = np.linalg.eig(a)
print(l)
print(u)

[1. 4.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


***Собственные значения матриц A и A.T совпадают.***

In [27]:
a.T # транспонированная матрица

array([[2, 2],
       [1, 3]])

In [28]:
l, u = np.linalg.eig(a.T)
print(l)
print(u)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [33]:
np.eye(3) # identity matrix, квадратная и её диагональ из 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
l, u = np.linalg.eig(np.eye(3))
print(l)
print(u)

[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


***Производительность.***

%%time - внутренняя функция, позволяет измерять ячейку

In [35]:
%%time

sum_value = np.sum(np.arange(10**7))
print(sum_value)

49999995000000
CPU times: total: 15.6 ms
Wall time: 54.5 ms


In [36]:
%%time
arr = 5*np.arange(10**7)

CPU times: total: 31.2 ms
Wall time: 80.3 ms


# Полезные ссылки

[Введение в Анализ Данных](https://mipt-stats.gitlab.io/jekyll/update/2020/02/01/ad.html)

[GitHub NumPy](https://github.com/numpy/numpy)

[Документация по NumPy](https://numpy.org/doc/stable/)

[mlcource.ai](https://mlcourse.ai)